### ISSUE TITLE
Supervised Learning ToDo's

### ISSUE THREAD

**Issue by juan190199** [juan190199/ML-From-Scratch#3]
- [ ] Regression: Weighted and Total Least Squares, Kernel Ridge Regression, LARS algorithm, orthogonal matching pursuit
- [ ] Generalized learning algorithms: Implement naive bayes for different likelihood distributions (Gaussian, Multinomial, etc)
- [x] Support vector machines
- [ ] Adaboost
- [ ] Neuroevolution
- [ ] Particle Swam Optimization
- [ ] Gradient boosting
- [ ] XGBoost
- [ ] Generalized linear model

**Comment by juan190199** [comment]
### Generalized learning algorithms

Implement naive bayes for different likelihood distributions (Gaussian, Multinomial, etc)
