### ISSUE TITLE
Unsupervised Learning's ToDo

### ISSUE THREAD

**Issue by juan190199** [juan190199/ML-From-Scratch#5]
- [ ] Kernel-PCA
- [ ] Local Linear Embedding
- [ ] Non-Negative Matrix Factorisation
- [ ] Independent Component Analysis
- [ ] Clustering
- [ ] Ensemble methods
